//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string CONTROL_PANEL {
            get {
                return ResourceManager.GetString("CONTROL_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Signals.
        /// </summary>
        public static string INPUT_SIGNALS {
            get {
                return ResourceManager.GetString("INPUT_SIGNALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save 10 thousand updated sampling points at most after simpling ends.
        /// </summary>
        public static string SAVE_TIP {
            get {
                return ResourceManager.GetString("SAVE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the displayed duration.
        /// </summary>
        public static string SET_NUM_SAM {
            get {
                return ResourceManager.GetString("SET_NUM_SAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the sampling period.
        /// </summary>
        public static string SET_SIMPLING_PERIOD {
            get {
                return ResourceManager.GetString("SET_SIMPLING_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show signal change chart.
        /// </summary>
        public static string SHOW_SIGNAL_CHANGE {
            get {
                return ResourceManager.GetString("SHOW_SIGNAL_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dynamic signal value Gauge.
        /// </summary>
        public static string SHOW_SIGNAL_VALUE {
            get {
                return ResourceManager.GetString("SHOW_SIGNAL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Change Chart.
        /// </summary>
        public static string SIGNAL_CHANGE_CH {
            get {
                return ResourceManager.GetString("SIGNAL_CHANGE_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Value.
        /// </summary>
        public static string SIGNAL_VALUE {
            get {
                return ResourceManager.GetString("SIGNAL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Value Gauge.
        /// </summary>
        public static string SIGNAL_VALUE_GA {
            get {
                return ResourceManager.GetString("SIGNAL_VALUE_GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple the sinusoidal signal or not.
        /// </summary>
        public static string SIM_SIN {
            get {
                return ResourceManager.GetString("SIM_SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple the square signal or not.
        /// </summary>
        public static string SIM_SQU {
            get {
                return ResourceManager.GetString("SIM_SQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple the triangle-wave signal or not.
        /// </summary>
        public static string SIM_TRI {
            get {
                return ResourceManager.GetString("SIM_TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed Duration:.
        /// </summary>
        public static string SIMPLING_DURATION {
            get {
                return ResourceManager.GetString("SIMPLING_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Period:.
        /// </summary>
        public static string SIMPLING_PERIOD {
            get {
                return ResourceManager.GetString("SIMPLING_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinusoidal signal.
        /// </summary>
        public static string SINUSOIDAL_SIGNAL {
            get {
                return ResourceManager.GetString("SINUSOIDAL_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square signal.
        /// </summary>
        public static string SQUARE_SIGNAL {
            get {
                return ResourceManager.GetString("SQUARE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or stop signal simpling and showing.
        /// </summary>
        public static string START_STOP_TIP {
            get {
                return ResourceManager.GetString("START_STOP_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TIME {
            get {
                return ResourceManager.GetString("TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel data saving!.
        /// </summary>
        public static string TIP_CANCEL {
            get {
                return ResourceManager.GetString("TIP_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is successfully saved!.
        /// </summary>
        public static string TIP_DATASAVED {
            get {
                return ResourceManager.GetString("TIP_DATASAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string TIP_ERROR {
            get {
                return ResourceManager.GetString("TIP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Data.
        /// </summary>
        public static string TIP_SAVINGDATA {
            get {
                return ResourceManager.GetString("TIP_SAVINGDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TIP_START {
            get {
                return ResourceManager.GetString("TIP_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TIP_STOP {
            get {
                return ResourceManager.GetString("TIP_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle-wave signal.
        /// </summary>
        public static string TRIANGLE_SIGNAL {
            get {
                return ResourceManager.GetString("TRIANGLE_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPCClient.
        /// </summary>
        public static string WINDOW_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
